-- SUPERSEDED — do not run.
-- The continuous age scoring formula (95 - age) was intentionally kept.
-- Category thresholds now use the raw capacity score directly, so the
-- displayed score and the portfolio category are always in sync.
-- No data migration is needed.
